### ISSUE TITLE
Plots not rendering in quick example

### ISSUE THREAD

**Issue by Alleno** [sol-eng/powerpoint#1]
On this page, I copied the code from the "quick example", and it doesn't render the plots:

https://github.com/sol-eng/powerpoint/blob/master/rendering-powerpoint.Rmd

I think there is an extra ``r''`` at the beginning of the r chunks

**Comment by nwstephens** [comment]
Thanks. I've fixed the issue and included an [explanation](https://support.rstudio.com/hc/en-us/articles/360018181633) of why I'm using `r ''` in my document.
